In [37]:
import requests
import pandas as pd
import time

pokemon_list = []

for i in range(1, 721):
    url = f"https://pokeapi.co/api/v2/pokemon/{i}"
    response = requests.get(url)

    if response.status_code != 200:
        continue

    data = response.json()

    name = data["name"]

    types = [t["type"]["name"] for t in data["types"]]
    type1 = types[0]
    type2 = types[1] if len(types) > 1 else None

    stats = {stat["stat"]["name"]: stat["base_stat"] for stat in data["stats"]}

    pokemon_list.append({
        "name": name,
        "type1": type1,
        "type2": type2,
        "hp": stats.get("hp"),
        "attack": stats.get("attack"),
        "defense": stats.get("defense"),
        "sp_attack": stats.get("special-attack"),
        "sp_defense": stats.get("special-defense"),
        "speed": stats.get("speed"),
    })

    time.sleep(0.2)

df = pd.DataFrame(pokemon_list)

df.head()

,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed
0,bulbasaur,grass,poison,45,49,49,65,65,45
1,ivysaur,grass,poison,60,62,63,80,80,60
2,venusaur,grass,poison,80,82,83,100,100,80
3,charmander,fire,NaN,39,52,43,60,50,65
4,charmeleon,fire,NaN,58,64,58,80,65,80

In [38]:
type_effectiveness = {
    "normal": {"rock": 0.5, "ghost": 0, "steel": 0.5},
    "fire": {"fire": 0.5, "water": 0.5, "grass": 2, "ice": 2, "bug": 2, "rock": 0.5, "dragon": 0.5, "steel": 2},
    "water": {"fire": 2, "water": 0.5, "grass": 0.5, "ground": 2, "rock": 2, "dragon": 0.5},
    "electric": {"water": 2, "electric": 0.5, "grass": 0.5, "ground": 0, "flying": 2, "dragon": 0.5},
    "grass": {"fire": 0.5, "water": 2, "grass": 0.5, "poison": 0.5, "ground": 2, "flying": 0.5, "bug": 0.5, "rock": 2, "dragon": 0.5, "steel": 0.5},
    "ice": {"fire": 0.5, "water": 0.5, "grass": 2, "ice": 0.5, "ground": 2, "flying": 2, "dragon": 2, "steel": 0.5},
    "fighting": {"normal": 2, "ice": 2, "poison": 0.5, "flying": 0.5, "psychic": 0.5, "bug": 0.5, "rock": 2, "ghost": 0, "dark": 2, "steel": 2, "fairy": 0.5},
    "poison": {"grass": 2, "poison": 0.5, "ground": 0.5, "rock": 0.5, "ghost": 0.5, "steel": 0, "fairy": 2},
    "ground": {"fire": 2, "electric": 2, "grass": 0.5, "poison": 2, "flying": 0, "bug": 0.5, "rock": 2, "steel": 2},
    "flying": {"electric": 0.5, "grass": 2, "fighting": 2, "bug": 2, "rock": 0.5, "steel": 0.5},
    "psychic": {"fighting": 2, "poison": 2, "psychic": 0.5, "dark": 0, "steel": 0.5},
    "bug": {"fire": 0.5, "grass": 2, "fighting": 0.5, "poison": 0.5, "flying": 0.5, "psychic": 2, "ghost": 0.5, "dark": 2, "steel": 0.5, "fairy": 0.5},
    "rock": {"fire": 2, "ice": 2, "fighting": 0.5, "ground": 0.5, "flying": 2, "bug": 2, "steel": 0.5},
    "ghost": {"normal": 0, "psychic": 2, "ghost": 2, "dark": 0.5},
    "dragon": {"dragon": 2, "steel": 0.5, "fairy": 0},
    "dark": {"fighting": 0.5, "psychic": 2, "ghost": 2, "dark": 0.5, "fairy": 0.5},
    "steel": {"fire": 0.5, "water": 0.5, "electric": 0.5, "ice": 2, "rock": 2, "steel": 0.5, "fairy": 2},
    "fairy": {"fire": 0.5, "fighting": 2, "poison": 0.5, "dragon": 2, "dark": 2, "steel": 0.5}
}

In [39]:
legendary_pokemon = {
    # Gen 1
    "articuno", "zapdos", "moltres", "mewtwo", "mew",

    # Gen 2
    "raikou", "entei", "suicune", "lugia", "ho-oh", "celebi",

    # Gen 3
    "regirock", "regice", "registeel",
    "latias", "latios",
    "kyogre", "groudon", "rayquaza",
    "jirachi", "deoxys",

    # Gen 4
    "uxie", "mesprit", "azelf",
    "dialga", "palkia", "heatran",
    "regigigas",
    "giratina", "cresselia",
    "phione", "manaphy", "darkrai",
    "shaymin", "arceus",

    # Gen 5
    "victini",
    "cobalion", "terrakion", "virizion",
    "tornadus", "thundurus", "landorus",
    "reshiram", "zekrom", "kyurem",
    "keldeo", "meloetta", "genesect",

    # Gen 6
    "xerneas", "yveltal", "zygarde",
    "diancie", "hoopa", "volcanion",

    # Gen 7
    "type-null", "silvally",
    "tapu-koko", "tapu-lele", "tapu-bulu", "tapu-fini",
    "cosmog", "cosmoem", "solgaleo", "lunala", "necrozma",
    "magearna", "marshadow", "zeraora", "meltan", "melmetal",

    # Gen 8
    "zacian", "zamazenta", "eternatus",
    "kubfu", "urshifu",
    "zarude",
    "regieleki", "regidrago",
    "glastrier", "spectrier",
    "calyrex",

    # Gen 9
    "wo-chien", "chien-pao", "ting-lu", "chi-yu",
    "koraidon", "miraidon",
    "walking-wake", "iron-leaves",
    "okidogi", "munkidori", "fezandipiti",
    "ogerpon",
    "terapagos"
}

In [40]:
df["is_legendary"] = df["name"].apply(lambda name: name in legendary_pokemon)
df[["name", "is_legendary"]].head(20)

          name  is_legendary
0    bulbasaur         False
1      ivysaur         False
2     venusaur         False
3   charmander         False
4   charmeleon         False
5    charizard         False
6     squirtle         False
7    wartortle         False
8    blastoise         False
9     caterpie         False
10     metapod         False
11  butterfree         False
12      weedle         False
13      kakuna         False
14    beedrill         False
15      pidgey         False
16   pidgeotto         False
17     pidgeot         False
18     rattata         False
19    raticate         False

In [41]:
def assign_role(row):
    if row["speed"] >= 100 and (row["attack"] >= 90 or row["sp_attack"] >= 90):
        return "fast attacker"
    
    if row["attack"] >= 100:
        return "physical attacker"
    
    if row["sp_attack"] >= 100:
        return "special attacker"
    
    if row["hp"] >= 80 and (row["defense"] >= 80 or row["sp_defense"] >= 80):
        return "bulky defender"
    
    if row["defense"] >= 90 or row["sp_defense"] >= 90:
        return "defensive support"
    
    return "balanced"

In [42]:
all_types = list(type_effectiveness.keys())

def get_type_multiplier(attacking_type, defender_type1, defender_type2=None):
    multiplier = type_effectiveness.get(attacking_type, {}).get(defender_type1, 1)
    
    if defender_type2 and not pd.isna(defender_type2):
        multiplier *= type_effectiveness.get(attacking_type, {}).get(defender_type2, 1)
    
    return multiplier


def get_defensive_profile(type1, type2=None):
    profile = {}
    
    for attacking_type in all_types:
        multiplier = get_type_multiplier(attacking_type, type1, type2)
        profile[attacking_type] = multiplier
    
    return profile


def get_real_weaknesses(type1, type2=None):
    profile = get_defensive_profile(type1, type2)
    return [attack_type for attack_type, multiplier in profile.items() if multiplier > 1]

In [43]:
def get_weaknesses(type1, type2):
    weaknesses = set(type_chart.get(type1, []))
    
    if type2:
        weaknesses.update(type_chart.get(type2, []))
    
    return list(weaknesses)

In [44]:
df["defensive_profile"] = df.apply(
    lambda row: get_defensive_profile(row["type1"], row["type2"]),
    axis=1
)

df["weaknesses"] = df.apply(
    lambda row: get_real_weaknesses(row["type1"], row["type2"]),
    axis=1
)

df["role"] = df.apply(assign_role, axis=1)

df[["name", "type1", "type2", "hp", "attack", "defense", "sp_attack", "sp_defense", "speed", "role"]].head(20)

df.head()

,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,is_legendary,defensive_profile,weaknesses,role
0,bulbasaur,grass,poison,45,49,49,65,65,45,False,"{'normal': 1, 'fire': 2, 'water': 0.5, 'electr...","[fire, ice, flying, psychic]",balanced
1,ivysaur,grass,poison,60,62,63,80,80,60,False,"{'normal': 1, 'fire': 2, 'water': 0.5, 'electr...","[fire, ice, flying, psychic]",balanced
2,venusaur,grass,poison,80,82,83,100,100,80,False,"{'normal': 1, 'fire': 2, 'water': 0.5, 'electr...","[fire, ice, flying, psychic]",special attacker
3,charmander,fire,NaN,39,52,43,60,50,65,False,"{'normal': 1, 'fire': 0.5, 'water': 2, 'electr...","[water, ground, rock]",balanced
4,charmeleon,fire,NaN,58,64,58,80,65,80,False,"{'normal': 1, 'fire': 0.5, 'water': 2, 'electr...","[water, ground, rock]",balanced

In [45]:
df[df["name"] == "charizard"][["name", "type1", "type2", "weaknesses", "defensive_profile"]]

,name,type1,type2,weaknesses,defensive_profile
5,charizard,fire,flying,"[water, electric, rock]","{'normal': 1, 'fire': 0.5, 'water': 2, 'electr..."

In [46]:
def recommend_teammates(selected_pokemon, df, playstyle="balanced", team_size=6, max_legendaries=0):
    selected_row = df[df["name"].str.lower() == selected_pokemon.lower()]
    
    if selected_row.empty:
        return f"{selected_pokemon} not found in dataset."
    
    # Allow both "offense" and "offensive"
    if playstyle == "offensive":
        playstyle = "offense"
    
    team = [selected_row.iloc[0].to_dict()]
    candidates = df[df["name"].str.lower() != selected_pokemon.lower()].copy()
    
    while len(team) < team_size:
        team_weaknesses = set()
        team_types = []
        team_roles = []
        
        for member in team:
            team_weaknesses.update(member["weaknesses"])
            team_roles.append(member["role"])
            
            team_types.append(member["type1"])
            
            if member["type2"] and not pd.isna(member["type2"]):
                team_types.append(member["type2"])
        
        # Count current legendaries
        legendary_count = sum(1 for member in team if member["is_legendary"])
        
        # Hard filter: if legendary limit reached, remove all legendary candidates
        if legendary_count >= max_legendaries:
            candidates = candidates[candidates["is_legendary"] == False]
        
        if candidates.empty:
            break
        
        def score_candidate(row):
            weaknesses = set(row["weaknesses"])
            weakness_overlap = len(team_weaknesses.intersection(weaknesses))
            
            type_duplication = 0
            
            if row["type1"] in team_types:
                type_duplication += 1
            
            if row["type2"] and not pd.isna(row["type2"]) and row["type2"] in team_types:
                type_duplication += 1
            
            role_duplication = team_roles.count(row["role"])
            
            atk = row["attack"]
            spa = row["sp_attack"]
            speed = row["speed"]
            hp = row["hp"]
            defense = row["defense"]
            spdef = row["sp_defense"]
            
            if playstyle == "offense":
                stat_score = (speed * 0.5) + (max(atk, spa) * 0.5)
            
            elif playstyle == "stall":
                stat_score = (hp * 0.4) + (defense * 0.3) + (spdef * 0.3)
            
            elif playstyle == "tank":
                stat_score = (max(atk, spa) * 0.5) + (hp * 0.3) + (defense * 0.2)
            
            else:  # balanced
                stat_score = (atk + spa + speed + hp + defense + spdef) / 6
            
            score = (
                weakness_overlap * 3
                + type_duplication * 2
                + role_duplication * 2
                - stat_score / 50
            )
            
            return score
        
        candidates["team_score"] = candidates.apply(score_candidate, axis=1)
        candidates = candidates.sort_values(by="team_score", ascending=True)
        
        next_pick = candidates.iloc[0]
        team.append(next_pick.to_dict())
        
        candidates = candidates[candidates["name"] != next_pick["name"]]
    
    return pd.DataFrame(team)

In [47]:
df.to_csv("pokemon_data_with_type_effectiveness.csv", index=False)

In [48]:
import requests
import pandas as pd

def get_pokemon_moves(pokemon_name):
    url = f"https://pokeapi.co/api/v2/pokemon/{pokemon_name.lower()}"
    response = requests.get(url)

    if response.status_code != 200:
        return []

    data = response.json()
    moves = []

    for move_entry in data["moves"]:
        move_name = move_entry["move"]["name"]
        move_url = move_entry["move"]["url"]

        move_response = requests.get(move_url)

        if move_response.status_code != 200:
            continue

        move_data = move_response.json()

        # Ignore status moves
        if move_data["damage_class"]["name"] == "status":
            continue

        # Ignore moves with no power
        if move_data["power"] is None:
            continue

        moves.append({
            "move": move_name,
            "type": move_data["type"]["name"],
            "power": move_data["power"],
            "accuracy": move_data["accuracy"],
            "damage_class": move_data["damage_class"]["name"]
        })

    return moves

In [49]:
pikachu_moves = get_pokemon_moves("pikachu")
pd.DataFrame(pikachu_moves).head(20)

             move      type  power  accuracy damage_class
0      mega-punch    normal     80      85.0     physical
1         pay-day    normal     40     100.0     physical
2   thunder-punch  electric     75     100.0     physical
3            slam    normal     80      75.0     physical
4     double-kick  fighting     30     100.0     physical
5       mega-kick    normal    120      75.0     physical
6        headbutt    normal     70     100.0     physical
7       body-slam    normal     85     100.0     physical
8       take-down    normal     90      85.0     physical
9     double-edge    normal    120     100.0     physical
10           surf     water     90     100.0      special
11     submission  fighting     80      80.0     physical
12       strength    normal     80     100.0     physical
13  thunder-shock  electric     40     100.0      special
14    thunderbolt  electric     90     100.0      special
15        thunder  electric    110      70.0      special
16            dig    ground     80     100.0     physical
17   quick-attack    normal     40     100.0     physical
18           rage    normal     20     100.0     physical
19          swift    normal     60       NaN      special

In [50]:
def score_move(move):
    accuracy = move["accuracy"] if move["accuracy"] is not None else 100
    return move["power"] * (accuracy / 100)

In [51]:
moves_df = pd.DataFrame(pikachu_moves)
moves_df["score"] = moves_df.apply(score_move, axis=1)
moves_df.sort_values(by="score", ascending=False).head(10)

           move      type  power  accuracy damage_class  score
33  focus-punch  fighting    150     100.0     physical  150.0
20   skull-bash    normal    130     100.0     physical  130.0
9   double-edge    normal    120     100.0     physical  120.0
39  volt-tackle  electric    120     100.0     physical  120.0
14  thunderbolt  electric     90     100.0      special   90.0
10         surf     water     90     100.0      special   90.0
5     mega-kick    normal    120      75.0     physical   90.0
48  wild-charge  electric     90     100.0     physical   90.0
31       uproar    normal     90     100.0      special   90.0
7     body-slam    normal     85     100.0     physical   85.0

In [52]:
def recommend_moves(pokemon_name, df, max_moves=4):
    moves = get_pokemon_moves(pokemon_name)
    moves_df = pd.DataFrame(moves)

    if moves_df.empty:
        return pd.DataFrame()

    pokemon_row = df[df["name"].str.lower() == pokemon_name.lower()].iloc[0]
    pokemon_types = {pokemon_row["type1"]}

    if pokemon_row["type2"] and not pd.isna(pokemon_row["type2"]):
        pokemon_types.add(pokemon_row["type2"])

    moves_df["score"] = moves_df.apply(score_move, axis=1)
    moves_df["is_stab"] = moves_df["type"].apply(lambda move_type: move_type in pokemon_types)

    selected_moves = []
    used_types = set()

    # 1. Always pick the best STAB move first
    stab_moves = moves_df[moves_df["is_stab"]].sort_values(by="score", ascending=False)

    if not stab_moves.empty:
        best_stab = stab_moves.iloc[0]
        selected_moves.append(best_stab)
        used_types.add(best_stab["type"])

    # 2. Fill remaining slots with strong coverage moves
    coverage_moves = moves_df.sort_values(by="score", ascending=False)

    for _, move in coverage_moves.iterrows():
        if len(selected_moves) >= max_moves:
            break

        if move["move"] in [m["move"] for m in selected_moves]:
            continue

        if move["type"] not in used_types:
            selected_moves.append(move)
            used_types.add(move["type"])

    return pd.DataFrame(selected_moves)

In [53]:
recommend_moves("charizard",df)

           move      type  power  accuracy damage_class  score  is_stab
50   blast-burn      fire    150      90.0      special  135.0     True
46  focus-punch  fighting    150     100.0     physical  150.0    False
62  giga-impact    normal    150      90.0     physical  135.0    False
18   solar-beam     grass    120     100.0      special  120.0    False

In [54]:
recommend_teammates("charizard", df, playstyle="offensive", max_legendaries=1)

,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,is_legendary,defensive_profile,weaknesses,role,team_score
0,charizard,fire,flying,78,84,78,109,85,100,False,"{'normal': 1, 'fire': 0.5, 'water': 2, 'electr...","[water, electric, rock]",fast attacker,NaN
1,haxorus,dragon,NaN,76,147,90,60,70,97,False,"{'normal': 1, 'fire': 0.5, 'water': 0.5, 'elec...","[ice, dragon, fairy]",physical attacker,-2.44
2,electrode,electric,NaN,60,50,70,80,80,150,False,"{'normal': 1, 'fire': 1, 'water': 1, 'electric...",[ground],balanced,-2.30
3,porygon-z,normal,NaN,85,80,70,135,75,90,False,"{'normal': 1, 'fire': 1, 'water': 1, 'electric...",[fighting],special attacker,-2.25
4,grumpig,psychic,NaN,80,45,65,90,110,80,False,"{'normal': 1, 'fire': 1, 'water': 1, 'electric...","[bug, ghost, dark]",bulky defender,-1.70
5,forretress,bug,steel,75,90,140,60,60,40,False,"{'normal': 0.5, 'fire': 4, 'water': 1, 'electr...",[fire],defensive support,-1.30

In [55]:
import os

os.makedirs("data/processed", exist_ok=True)

df.to_csv("data/processed/pokemon_final.csv", index=False)

print("Saved pokemon_final.csv")

Saved pokemon_final.csv